# Generated by Django 3.0.4 on 2020-03-18 09:22

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter brand name', max_length=30)),
                ('contact_name', models.CharField(blank=True, help_text='Enter contact person name', max_length=30)),
                ('contact_number', phone_field.models.PhoneField(blank=True, help_text='Enter contact phone number', max_length=31)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the brand', max_length=1000)),
                ('website', models.URLField(blank=True, help_text='Enter brand website address')),
                ('upload', models.ImageField(help_text='upload brand image', upload_to='assets/brands/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
                ('category', models.ManyToManyField(to='category.Category')),
            ],
        ),
    ]
