# Generated by Django 3.0.2 on 2020-02-19 09:28

import brand.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter brand name', max_length=30)),
                ('contact_name', models.CharField(blank=True, help_text='Enter contact person name', max_length=30)),
                ('contact_number', phone_field.models.PhoneField(blank=True, help_text='Enter contact phone number', max_length=31)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the brand', max_length=1000)),
                ('website', models.URLField(blank=True, help_text='Enter brand website address')),
                ('upload', models.ImageField(help_text='upload brand image', upload_to=brand.models.user_directory_path)),
            ],
        ),
    ]
