# Generated by Django 3.0.2 on 2020-02-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
        ('brand', '0002_auto_20200219_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='upload',
            field=models.ImageField(help_text='upload brand image', upload_to='assets/brands/'),
        ),
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.PartCategory')),
            ],
        ),
    ]
