# Generated by Django 3.0.2 on 2020-02-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_auto_20200226_0632'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.Category'),
        ),
    ]
