# Generated by Django 3.0.3 on 2020-03-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200226_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercategory',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
