# Generated by Django 3.0.4 on 2020-03-18 09:22

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import part.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmaker', '0001_initial'),
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        ('seller', '0001_initial'),
        ('areapincode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=70)),
                ('part_number', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('OM', 'OEM'), ('AM', 'AfterMarket')], default='OM', max_length=2)),
                ('feature', djrichtextfield.models.RichTextField()),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the part', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Auto Parts',
            },
        ),
        migrations.CreateModel(
            name='AutoPartSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('out_stock', models.PositiveIntegerField(default=0)),
                ('stock_in_process', models.PositiveIntegerField(default=0)),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('availability', models.ManyToManyField(to='areapincode.AreaPincode')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload autopart image', upload_to=part.models.get_image_path)),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('carmaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmaker.CarMaker')),
                ('carmakermodel', models.ManyToManyField(to='carmaker.CarMakerModel')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('category', models.ManyToManyField(to='category.Category')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('brand', models.ManyToManyField(to='brand.Brand')),
            ],
        ),
    ]
