# Generated by Django 3.0.2 on 2020-02-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_auto_20200226_0632'),
        ('seller', '0002_auto_20200226_0632'),
        ('brand', '0004_auto_20200226_0632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='part.Category'),
        ),
    ]
