# Generated by Django 3.0.2 on 2020-02-26 07:46

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200226_0746'),
        ('category', '0001_initial'),
        ('brand', '0005_auto_20200226_0746'),
        ('part', '0003_auto_20200226_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('feature', djrichtextfield.models.RichTextField()),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the part', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
