# Generated by Django 3.0.2 on 2020-02-26 09:04

from django.db import migrations, models
import django.db.models.deletion
import part.models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20200226_0746'),
        ('part', '0004_auto_20200226_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPartImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload autopart image', upload_to=part.models.get_image_path)),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
        ),
    ]
