# Generated by Django 3.0.2 on 2020-02-26 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_autopartbrand_autopartimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='part_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
