# Generated by Django 3.0.2 on 2020-02-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0006_autopart_part_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoPartImages',
            new_name='AutoPartPicture',
        ),
    ]
