# Generated by Django 3.0.2 on 2020-02-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_auto_20200227_1000'),
        ('part', '0011_auto_20200227_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
