# Generated by Django 3.0.2 on 2020-02-28 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_auto_20200227_1000'),
        ('brand', '0005_auto_20200226_0746'),
        ('part', '0015_auto_20200227_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartbrand',
            name='autopart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart'),
        ),
        migrations.AlterField(
            model_name='autopartbrand',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
        migrations.AlterField(
            model_name='autopartcategory',
            name='autopart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart'),
        ),
        migrations.AlterField(
            model_name='autopartcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
