# Generated by Django 3.0.2 on 2020-02-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0016_auto_20200228_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartcategory',
            name='autopart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart'),
        ),
    ]
