# Generated by Django 3.0.2 on 2020-02-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0018_auto_20200228_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopartbrand',
            name='autopart',
        ),
        migrations.RemoveField(
            model_name='autopartbrand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='autopartcategory',
            name='autopart',
        ),
        migrations.RemoveField(
            model_name='autopartcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='autopartpicture',
            name='autopart',
        ),
        migrations.DeleteModel(
            name='AutoPart',
        ),
        migrations.DeleteModel(
            name='AutoPartBrand',
        ),
        migrations.DeleteModel(
            name='AutoPartCategory',
        ),
        migrations.DeleteModel(
            name='AutoPartPicture',
        ),
    ]
