# Generated by Django 3.0.2 on 2020-02-28 09:06

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import part.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0005_auto_20200226_0746'),
        ('category', '0021_auto_20200228_0755'),
        ('part', '0019_auto_20200228_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=70)),
                ('part_number', models.CharField(max_length=100)),
                ('feature', djrichtextfield.models.RichTextField()),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the part', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload autopart image', upload_to=part.models.get_image_path)),
                ('autopart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
        ),
    ]
