# Generated by Django 3.0.2 on 2020-02-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0020_autopart_autopartbrand_autopartcategory_autopartpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartpicture',
            name='autopart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart'),
        ),
    ]
