# Generated by Django 3.0.2 on 2020-02-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0021_auto_20200228_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartpicture',
            name='autopart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart'),
        ),
    ]
