# Generated by Django 3.0.3 on 2020-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0023_auto_20200228_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='origin',
            field=models.CharField(choices=[('OM', 'OEM'), ('AM', 'AfterMarket')], default='OM', max_length=2),
        ),
    ]
