# Generated by Django 3.0.2 on 2020-03-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200303_1113'),
        ('part', '0026_autopartcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartseller',
            name='autopart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart'),
        ),
        migrations.RemoveField(
            model_name='autopartseller',
            name='seller',
        ),
        migrations.AddField(
            model_name='autopartseller',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
