# Generated by Django 3.0.2 on 2020-03-06 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20200304_0625'),
        ('part', '0028_auto_20200305_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autopart',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AutoPartCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.AutoPart')),
                ('carmaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.CarMaker')),
                ('carmodel', models.ManyToManyField(to='car.CarModel')),
            ],
        ),
    ]
