# Generated by Django 3.0.2 on 2020-03-06 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
         ('part', '0028_auto_20200305_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autopart',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        )
    ]


