# Generated by Django 3.0.4 on 2020-03-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0029_auto_20200306_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autopart',
            options={'verbose_name_plural': 'Auto Parts'},
        ),
    ]
