# Generated by Django 3.0.2 on 2020-02-03 13:06

import Car.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelline', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), Car.models.max_value_current_year], verbose_name='year')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelLine',
        ),
        migrations.RemoveField(
            model_name='modellisting',
            name='modification',
        ),
        migrations.DeleteModel(
            name='ModelYear',
        ),
        migrations.RenameModel(
            old_name='Maker',
            new_name='CarMaker',
        ),
        migrations.DeleteModel(
            name='ModelListing',
        ),
        migrations.DeleteModel(
            name='ModelModification',
        ),
        migrations.AddField(
            model_name='carlist',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.CarMaker'),
        ),
    ]
