# Generated by Django 3.0.2 on 2020-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_auto_20200203_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='modelline',
            field=models.CharField(max_length=100),
        ),
    ]
