# Generated by Django 3.0.2 on 2020-03-04 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200218_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.CarMaker'),
        ),
    ]
