# Generated by Django 3.0.4 on 2020-03-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20200304_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmaker',
            options={'verbose_name_plural': 'Car Makers'},
        ),
    ]
