# Generated by Django 3.0.2 on 2020-02-12 07:09

import Car.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_auto_20200203_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelline', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), Car.models.max_value_current_year], verbose_name='year')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.CarMaker')),
            ],
        ),
        migrations.DeleteModel(
            name='CarList',
        ),
    ]
