# Generated by Django 3.0.2 on 2020-02-12 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_auto_20200212_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodelline',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
