# Generated by Django 3.0.2 on 2020-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_carmodelline_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodelline',
            name='modification',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodelline',
            name='modelline',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
