# Generated by Django 3.0.2 on 2020-02-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_auto_20200228_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_category',
        ),
    ]
