# Generated by Django 3.0.4 on 2020-03-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_auto_20200228_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
