# Generated by Django 3.0.2 on 2020-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('type', models.SmallIntegerField(max_length=2)),
                ('registration_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
