# Generated by Django 3.0.2 on 2020-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areapincode', '0002_auto_20200305_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areapincode',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
