# Generated by Django 3.0.4 on 2020-03-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areapincode', '0003_auto_20200305_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areapincode',
            options={'verbose_name_plural': 'Delivery Pincodes'},
        ),
    ]
